runtime: go
api_version: go1

handlers:

  - url: /en-privacy
    static_files: static/en-privacy.txt
    upload: static/en-privacy.txt

  - url: /de-privacy
    static_files: static/de-privacy.txt
    upload: static/de-privacy.txt

  - url: /fr-privacy
    static_files: static/fr-privacy.txt
    upload: static/fr-privacy.txt

  - url: /.*
    secure: always
    script: _go_app
